name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8 # Specify your pnpm version
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build # Replace with your build command
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/demo/dist # Replace with your build output directory
